@extends('layouts.app')

@section('bg-header') color-bg-green @endsection

@section('content')

<section id="pspr" class="about">
    <div class="container" data-aos="fade-up">
        <div class="pt-5">
            <h2 class="page-title">Produksi dan Siaran Program Radio</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, labore facere quisquam id accusamus reprehenderit expedita doloremque tempora nemo commodi odit voluptates sint ex! Modi, sequi. Excepturi soluta eligendi omnis tenetur reprehenderit quia, tempora ullam quibusdam expedita, inventore laudantium debitis at hic amet sint quasi porro. Libero eos tempore eum exercitationem totam temporibus ipsa! Ipsum dolores laborum placeat, earum quas quidem. Eum iusto dolor rerum omnis dignissimos, commodi voluptates molestiae laboriosam suscipit eligendi sint dolorum sed voluptate provident neque quo! Quae aut, nobis blanditiis esse dolor recusandae, necessitatibus deserunt autem modi eveniet accusantium repellat impedit nulla vel qui optio vitae in debitis ex error ipsam dolorem enim! Earum aut fugiat aliquid sunt. Obcaecati, perferendis dolores! Maiores iste corporis ad commodi saepe, sed totam, incidunt nemo similique tempora tempore harum sapiente aut repellendus est animi pariatur ab possimus quos et provident necessitatibus ratione. Nesciunt, dignissimos, dolorum esse eum facilis cum iusto dolorem quos suscipit ipsam accusantium doloribus. Corrupti animi, aliquid iusto asperiores doloribus optio facere eum, culpa deserunt accusantium odit eos natus ab non assumenda quia, et nisi sapiente nam perspiciatis repellat mollitia architecto vel. Corporis nemo id, velit ipsum, optio voluptatem hic ullam dignissimos assumenda quo qui quasi amet sequi eligendi quia laudantium alias quisquam. Qui veritatis quis, voluptatem dolorem fugiat tenetur non inventore quidem quibusdam praesentium debitis nihil soluta vitae earum cum perspiciatis voluptas, eveniet eum dignissimos adipisci voluptatibus corrupti? Vel unde illum amet. Tenetur reprehenderit, magnam error unde perferendis iste autem et laborum obcaecati, recusandae a, vero tempore.</p>
        </div>
    </div>
</section>
<section id="pspt" class="about">
    <div class="container" data-aos="fade-up">
        <div class="row">
            <h2 class="page-title">Produksi dan Siaran Program Televisi</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, labore facere quisquam id accusamus reprehenderit expedita doloremque tempora nemo commodi odit voluptates sint ex! Modi, sequi. Excepturi soluta eligendi omnis tenetur reprehenderit quia, tempora ullam quibusdam expedita, inventore laudantium debitis at hic amet sint quasi porro. Libero eos tempore eum exercitationem totam temporibus ipsa! Ipsum dolores laborum placeat, earum quas quidem. Eum iusto dolor rerum omnis dignissimos, commodi voluptates molestiae laboriosam suscipit eligendi sint dolorum sed voluptate provident neque quo! Quae aut, nobis blanditiis esse dolor recusandae, necessitatibus deserunt autem modi eveniet accusantium repellat impedit nulla vel qui optio vitae in debitis ex error ipsam dolorem enim! Earum aut fugiat aliquid sunt. Obcaecati, perferendis dolores! Maiores iste corporis ad commodi saepe, sed totam, incidunt nemo similique tempora tempore harum sapiente aut repellendus est animi pariatur ab possimus quos et provident necessitatibus ratione. Nesciunt, dignissimos, dolorum esse eum facilis cum iusto dolorem quos suscipit ipsam accusantium doloribus. Corrupti animi, aliquid iusto asperiores doloribus optio facere eum, culpa deserunt accusantium odit eos natus ab non assumenda quia, et nisi sapiente nam perspiciatis repellat mollitia architecto vel. Corporis nemo id, velit ipsum, optio voluptatem hic ullam dignissimos assumenda quo qui quasi amet sequi eligendi quia laudantium alias quisquam. Qui veritatis quis, voluptatem dolorem fugiat tenetur non inventore quidem quibusdam praesentium debitis nihil soluta vitae earum cum perspiciatis voluptas, eveniet eum dignissimos adipisci voluptatibus corrupti? Vel unde illum amet. Tenetur reprehenderit, magnam error unde perferendis iste autem et laborum obcaecati, recusandae a, vero tempore.</p>
        </div>
    </div>
</section>
<section id="tkj" class="about">
    <div class="container" data-aos="fade-up">
        <div class="row">
            <h2 class="page-title">Teknik Komputer Jaringan</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, labore facere quisquam id accusamus reprehenderit expedita doloremque tempora nemo commodi odit voluptates sint ex! Modi, sequi. Excepturi soluta eligendi omnis tenetur reprehenderit quia, tempora ullam quibusdam expedita, inventore laudantium debitis at hic amet sint quasi porro. Libero eos tempore eum exercitationem totam temporibus ipsa! Ipsum dolores laborum placeat, earum quas quidem. Eum iusto dolor rerum omnis dignissimos, commodi voluptates molestiae laboriosam suscipit eligendi sint dolorum sed voluptate provident neque quo! Quae aut, nobis blanditiis esse dolor recusandae, necessitatibus deserunt autem modi eveniet accusantium repellat impedit nulla vel qui optio vitae in debitis ex error ipsam dolorem enim! Earum aut fugiat aliquid sunt. Obcaecati, perferendis dolores! Maiores iste corporis ad commodi saepe, sed totam, incidunt nemo similique tempora tempore harum sapiente aut repellendus est animi pariatur ab possimus quos et provident necessitatibus ratione. Nesciunt, dignissimos, dolorum esse eum facilis cum iusto dolorem quos suscipit ipsam accusantium doloribus. Corrupti animi, aliquid iusto asperiores doloribus optio facere eum, culpa deserunt accusantium odit eos natus ab non assumenda quia, et nisi sapiente nam perspiciatis repellat mollitia architecto vel. Corporis nemo id, velit ipsum, optio voluptatem hic ullam dignissimos assumenda quo qui quasi amet sequi eligendi quia laudantium alias quisquam. Qui veritatis quis, voluptatem dolorem fugiat tenetur non inventore quidem quibusdam praesentium debitis nihil soluta vitae earum cum perspiciatis voluptas, eveniet eum dignissimos adipisci voluptatibus corrupti? Vel unde illum amet. Tenetur reprehenderit, magnam error unde perferendis iste autem et laborum obcaecati, recusandae a, vero tempore.</p>
        </div>
    </div>
</section>
<section id="rpl" class="about">
    <div class="container" data-aos="fade-up">
        <div class="row">
            <h2 class="page-title">Rekayasa Perangkat Lunak</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, labore facere quisquam id accusamus reprehenderit expedita doloremque tempora nemo commodi odit voluptates sint ex! Modi, sequi. Excepturi soluta eligendi omnis tenetur reprehenderit quia, tempora ullam quibusdam expedita, inventore laudantium debitis at hic amet sint quasi porro. Libero eos tempore eum exercitationem totam temporibus ipsa! Ipsum dolores laborum placeat, earum quas quidem. Eum iusto dolor rerum omnis dignissimos, commodi voluptates molestiae laboriosam suscipit eligendi sint dolorum sed voluptate provident neque quo! Quae aut, nobis blanditiis esse dolor recusandae, necessitatibus deserunt autem modi eveniet accusantium repellat impedit nulla vel qui optio vitae in debitis ex error ipsam dolorem enim! Earum aut fugiat aliquid sunt. Obcaecati, perferendis dolores! Maiores iste corporis ad commodi saepe, sed totam, incidunt nemo similique tempora tempore harum sapiente aut repellendus est animi pariatur ab possimus quos et provident necessitatibus ratione. Nesciunt, dignissimos, dolorum esse eum facilis cum iusto dolorem quos suscipit ipsam accusantium doloribus. Corrupti animi, aliquid iusto asperiores doloribus optio facere eum, culpa deserunt accusantium odit eos natus ab non assumenda quia, et nisi sapiente nam perspiciatis repellat mollitia architecto vel. Corporis nemo id, velit ipsum, optio voluptatem hic ullam dignissimos assumenda quo qui quasi amet sequi eligendi quia laudantium alias quisquam. Qui veritatis quis, voluptatem dolorem fugiat tenetur non inventore quidem quibusdam praesentium debitis nihil soluta vitae earum cum perspiciatis voluptas, eveniet eum dignissimos adipisci voluptatibus corrupti? Vel unde illum amet. Tenetur reprehenderit, magnam error unde perferendis iste autem et laborum obcaecati, recusandae a, vero tempore.</p>
        </div>
    </div>
</section>
<section id="mm" class="about">
    <div class="container" data-aos="fade-up">
        <div class="row">
            <h2 class="page-title">Multimedia</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, labore facere quisquam id accusamus reprehenderit expedita doloremque tempora nemo commodi odit voluptates sint ex! Modi, sequi. Excepturi soluta eligendi omnis tenetur reprehenderit quia, tempora ullam quibusdam expedita, inventore laudantium debitis at hic amet sint quasi porro. Libero eos tempore eum exercitationem totam temporibus ipsa! Ipsum dolores laborum placeat, earum quas quidem. Eum iusto dolor rerum omnis dignissimos, commodi voluptates molestiae laboriosam suscipit eligendi sint dolorum sed voluptate provident neque quo! Quae aut, nobis blanditiis esse dolor recusandae, necessitatibus deserunt autem modi eveniet accusantium repellat impedit nulla vel qui optio vitae in debitis ex error ipsam dolorem enim! Earum aut fugiat aliquid sunt. Obcaecati, perferendis dolores! Maiores iste corporis ad commodi saepe, sed totam, incidunt nemo similique tempora tempore harum sapiente aut repellendus est animi pariatur ab possimus quos et provident necessitatibus ratione. Nesciunt, dignissimos, dolorum esse eum facilis cum iusto dolorem quos suscipit ipsam accusantium doloribus. Corrupti animi, aliquid iusto asperiores doloribus optio facere eum, culpa deserunt accusantium odit eos natus ab non assumenda quia, et nisi sapiente nam perspiciatis repellat mollitia architecto vel. Corporis nemo id, velit ipsum, optio voluptatem hic ullam dignissimos assumenda quo qui quasi amet sequi eligendi quia laudantium alias quisquam. Qui veritatis quis, voluptatem dolorem fugiat tenetur non inventore quidem quibusdam praesentium debitis nihil soluta vitae earum cum perspiciatis voluptas, eveniet eum dignissimos adipisci voluptatibus corrupti? Vel unde illum amet. Tenetur reprehenderit, magnam error unde perferendis iste autem et laborum obcaecati, recusandae a, vero tempore.</p>
        </div>
    </div>
</section>
<section id="upw" class="about">
    <div class="container" data-aos="fade-up">
        <div class="row">
            <h2 class="page-title">Usaha Perjalanan Wisata</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, labore facere quisquam id accusamus reprehenderit expedita doloremque tempora nemo commodi odit voluptates sint ex! Modi, sequi. Excepturi soluta eligendi omnis tenetur reprehenderit quia, tempora ullam quibusdam expedita, inventore laudantium debitis at hic amet sint quasi porro. Libero eos tempore eum exercitationem totam temporibus ipsa! Ipsum dolores laborum placeat, earum quas quidem. Eum iusto dolor rerum omnis dignissimos, commodi voluptates molestiae laboriosam suscipit eligendi sint dolorum sed voluptate provident neque quo! Quae aut, nobis blanditiis esse dolor recusandae, necessitatibus deserunt autem modi eveniet accusantium repellat impedit nulla vel qui optio vitae in debitis ex error ipsam dolorem enim! Earum aut fugiat aliquid sunt. Obcaecati, perferendis dolores! Maiores iste corporis ad commodi saepe, sed totam, incidunt nemo similique tempora tempore harum sapiente aut repellendus est animi pariatur ab possimus quos et provident necessitatibus ratione. Nesciunt, dignissimos, dolorum esse eum facilis cum iusto dolorem quos suscipit ipsam accusantium doloribus. Corrupti animi, aliquid iusto asperiores doloribus optio facere eum, culpa deserunt accusantium odit eos natus ab non assumenda quia, et nisi sapiente nam perspiciatis repellat mollitia architecto vel. Corporis nemo id, velit ipsum, optio voluptatem hic ullam dignissimos assumenda quo qui quasi amet sequi eligendi quia laudantium alias quisquam. Qui veritatis quis, voluptatem dolorem fugiat tenetur non inventore quidem quibusdam praesentium debitis nihil soluta vitae earum cum perspiciatis voluptas, eveniet eum dignissimos adipisci voluptatibus corrupti? Vel unde illum amet. Tenetur reprehenderit, magnam error unde perferendis iste autem et laborum obcaecati, recusandae a, vero tempore.</p>
        </div>
    </div>
</section>

@endsection